version: '3.2'

services:

  postgres:
    restart: 'always'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=spawnuser
      - POSTGRES_DB=spawn
      - POSTGRES_PASSWORD=spawn-pg-test-password
    build: './scripts/db'

  redis:
    image: "redis:alpine"
    restart: 'always'
    ports:
      - '6379:6379'
