version: '3.2'

services:

  rest:
    environment:
      - ENV="Test"
      - QUEUE_URL=amqp://rabbit:5672
      - CACHE_URL=redis://redis:6379
    restart: 'always'
    ports:
      - '8080:8080'
    container_name: rest
    build:
      context: .
      dockerfile: ./Dockerfile.web
    depends_on:
      - backend
      - redis
    links:
      - backend
      - redis

  backend:
    environment:
      - ENV="Test"
      - DATABASE_URL=postgresql://spawnuser:spawn-pg-test-password@postgres/spawn?sslmode=disable
      - QUEUE_URL=amqp://rabbit:5672
      - CACHE_URL=redis://redis:6379
    restart: 'always'
    ports:
      - '7887:7887'
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    depends_on:
      - postgres
      - redis
      - rabbit
    links:
      - postgres
      - redis

#  postgres:
#    restart: 'always'
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_USER=spawnuser
#      - POSTGRES_DB=spawn
#      - POSTGRES_PASSWORD=spawn-pg-test-password
#    build: './scripts/db'

#  redis:
#    image: "redis:alpine"
#    restart: 'always'
#    ports:
#      - '6379:6379'
